//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Schedules {
    
    private SchedulesJob[] jobField;
    
    private SchedulesTrigger[] triggerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Job")]
    public SchedulesJob[] Job {
        get {
            return this.jobField;
        }
        set {
            this.jobField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trigger")]
    public SchedulesTrigger[] Trigger {
        get {
            return this.triggerField;
        }
        set {
            this.triggerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SchedulesJob {
    
    private string nameField;
    
    private string groupField;
    
    private string descriptionField;
    
    private string jobtypeField;
    
    private bool durableField;
    
    private bool recoverField;
    
    private SchedulesJobEntry[] jobDataMapField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Jobtype {
        get {
            return this.jobtypeField;
        }
        set {
            this.jobtypeField = value;
        }
    }
    
    /// <remarks/>
    public bool Durable {
        get {
            return this.durableField;
        }
        set {
            this.durableField = value;
        }
    }
    
    /// <remarks/>
    public bool Recover {
        get {
            return this.recoverField;
        }
        set {
            this.recoverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Entry", IsNullable=false)]
    public SchedulesJobEntry[] JobDataMap {
        get {
            return this.jobDataMapField;
        }
        set {
            this.jobDataMapField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SchedulesJobEntry {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SchedulesTrigger {
    
    private SchedulesTriggerCalendarInterval calendarIntervalField;
    
    private SchedulesTriggerCron cronField;
    
    private SchedulesTriggerSimple simpleField;
    
    /// <remarks/>
    public SchedulesTriggerCalendarInterval CalendarInterval {
        get {
            return this.calendarIntervalField;
        }
        set {
            this.calendarIntervalField = value;
        }
    }
    
    /// <remarks/>
    public SchedulesTriggerCron Cron {
        get {
            return this.cronField;
        }
        set {
            this.cronField = value;
        }
    }
    
    /// <remarks/>
    public SchedulesTriggerSimple Simple {
        get {
            return this.simpleField;
        }
        set {
            this.simpleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SchedulesTriggerCalendarInterval {
    
    private string nameField;
    
    private string groupField;
    
    private string descriptionField;
    
    private string jobNameField;
    
    private string jobGroupField;
    
    private string misfireInstructionField;
    
    private ushort repeatIntervalField;
    
    private string repeatIntervalUnitField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string JobName {
        get {
            return this.jobNameField;
        }
        set {
            this.jobNameField = value;
        }
    }
    
    /// <remarks/>
    public string JobGroup {
        get {
            return this.jobGroupField;
        }
        set {
            this.jobGroupField = value;
        }
    }
    
    /// <remarks/>
    public string MisfireInstruction {
        get {
            return this.misfireInstructionField;
        }
        set {
            this.misfireInstructionField = value;
        }
    }
    
    /// <remarks/>
    public ushort RepeatInterval {
        get {
            return this.repeatIntervalField;
        }
        set {
            this.repeatIntervalField = value;
        }
    }
    
    /// <remarks/>
    public string RepeatIntervalUnit {
        get {
            return this.repeatIntervalUnitField;
        }
        set {
            this.repeatIntervalUnitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SchedulesTriggerCron {
    
    private string nameField;
    
    private string groupField;
    
    private string descriptionField;
    
    private string jobNameField;
    
    private string jobGroupField;
    
    private string misfireInstructionField;
    
    private string cronExpressionField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string JobName {
        get {
            return this.jobNameField;
        }
        set {
            this.jobNameField = value;
        }
    }
    
    /// <remarks/>
    public string JobGroup {
        get {
            return this.jobGroupField;
        }
        set {
            this.jobGroupField = value;
        }
    }
    
    /// <remarks/>
    public string MisfireInstruction {
        get {
            return this.misfireInstructionField;
        }
        set {
            this.misfireInstructionField = value;
        }
    }
    
    /// <remarks/>
    public string CronExpression {
        get {
            return this.cronExpressionField;
        }
        set {
            this.cronExpressionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SchedulesTriggerSimple {
    
    private string nameField;
    
    private string groupField;
    
    private string descriptionField;
    
    private string jobNameField;
    
    private string jobGroupField;
    
    private string misfireInstructionField;
    
    private sbyte repeatCountField;
    
    private ushort repeatIntervalField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string JobName {
        get {
            return this.jobNameField;
        }
        set {
            this.jobNameField = value;
        }
    }
    
    /// <remarks/>
    public string JobGroup {
        get {
            return this.jobGroupField;
        }
        set {
            this.jobGroupField = value;
        }
    }
    
    /// <remarks/>
    public string MisfireInstruction {
        get {
            return this.misfireInstructionField;
        }
        set {
            this.misfireInstructionField = value;
        }
    }
    
    /// <remarks/>
    public sbyte RepeatCount {
        get {
            return this.repeatCountField;
        }
        set {
            this.repeatCountField = value;
        }
    }
    
    /// <remarks/>
    public ushort RepeatInterval {
        get {
            return this.repeatIntervalField;
        }
        set {
            this.repeatIntervalField = value;
        }
    }
}
